server:
  port: 8080
spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Devuser@12
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
